language: go
go:
- "1.6"
env:
  global:
  - GIT_BRANCH=
  - GITHUB_REPO=Seklfreak/discord-image-downloader-go
notifications:
  email:
    recipients:
    - codeskyblue@gmail.com
    on_success: always
    on_failure: always
before_install: []
script:
- bash build.sh
after_success:
- echo done
