language: go
go:
- "1.6"
env:
  global:
  - GIT_BRANCH=
  - GITHUB_REPO=ory-am/hydra
notifications:
  email:
    recipients:
    - ""
    on_success: always
    on_failure: always
before_install: []
script:
- bash build.sh
after_success:
- echo done
